Fix PR #122. Add helper
saltstack/salt-windows-msi pull request #123
Opened 2021-11-07 13:45 UTC by marbx

Re-adding 2 files accidentally removed in PR 122
- tests/config_tests/MINION_CONFIG_1.test
- tests/config_tests/MINION_CONFIG_1.expected

![image](https://user-images.githubusercontent.com/8489107/140647628-82235a90-ac30-4621-86bc-3055fd03a8a8.png)

Adding a helper command

2021-11-08 18:12 UTC, twangboy requested changes

2021-11-08 18:12 UTC, twangboy commented on tests/config_tests/MINION_CONFIG_1.expected
> +master: Anna
Those tests weren't removed... they were renamed to follow the naming scheme of all the others. Perhaps we need to decide on a naming scheme.

2021-11-27 08:36 UTC, marbx commented on tests/config_tests/MINION_CONFIG_1.expected
> +master: Anna
This is the only test regarding the [`MINION_CONFIG` property](https://github.com/saltstack/salt-windows-msi/#property-minion_config) and you removed it accidentally. 
Search for `MINION_CONFIG` in *.test files or Anna in any file.
Maybe you have it on a local branch. Never mind.

I renamed to follow the naming scheme:

        renamed:    MINION_CONFIG_1.expected -> default_config_minion_config.expected
        renamed:    MINION_CONFIG_1.test -> default_config_minion_config.test

It's very satisfactory that the config tests are run automatic!

2021-12-03 18:31 UTC, twangboy approved these changes

2021-12-03 18:32 UTC, merged